import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider, getSession } from "next-auth/react";
import { ArticleProvider } from "@/context/ArticleContext";

// Define the Inter font
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// This is a server component where we can fetch the session
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <SessionProvider>
      <html lang="en">
        <body className={inter.className}>
          <ArticleProvider>
              {children}
          </ArticleProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
